### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by lbschenkel**
Hi, I have noticed your effort in modernizing the codebase. That is awesome! I'm greatly interested in the outcome.

I have fixed two issues the caused the core dumps you were experiencing. At least it made them go away in my system.

Note that there are other issues in the codebase (there are still cases in which it assumes that all keys are RSA). But at least with these two fixes it does not crash, which is a good start.

### CODE REVIEW

**Comment by toonetown** [comment]
Wow!  Thank you so much for helping out with this.  These look great.  I plan on merging them in - but, honestly, I didn't think that anyone was going to be following/submitting PRs to this fork.  I am going to clean up my `project-update` branch, so that it can perhaps have a better chance of getting merged upstream (maybe I'll create separate upstream PRs for each "thing" I fix) and start merging them into this master.  I may ask if you could re-submit this PR against the master branch once I've done that...but I'm not quite sure how I want to manage this fork yet.  I'll keep you posted here.

**Comment by lbschenkel** [comment]
Sure, my PR was just to communicate to you regarding the fixes. Feel free to take them in, or copy and paste, or just tell me when and where to resubmit. I'm an interested user of this project and I'll try to help in any way I can to make this codebase "alive" again.

**Comment by toonetown** [comment]
There are also a few fixes in another fork at https://github.com/mrene/KeychainToken - I might look through there and see if there is anything that would be "nice" to include.

Looks like they ran into the same certificate dereferencing issue...but I think your solution is a bit cleaner.  I do like the idea of having a standalone makefile too (which could maybe be used for homebrew, etc).

Anyway - it's great that there is another interested user.  The only reason I'd ask that you resubmit your PR is so that you can get credit for it in the commit log...I don't want to just copy/paste your fix without attribution 😄

**Comment by lbschenkel** [comment]
I already have a working `Portfile` (MacPorts) that builds my (your) branch. If you use MacPorts and are interested in that I can make it available to you.

**Comment by toonetown** [comment]
The Portfile would be great...it would give me direction for how to do the homebrew version as well.

Would you mind resubmitting this PR as one that is based off of master (probably as two separate ones...one for each commit)?

Thank you so much!

**Pull request closed without merging**
